"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type SupplierQuote={poId:string;poNumber:string;supplierId:string;projectId?:string;totalAmount?:number|string;status?:string};
type PurchaseOrder={poId:string;poNumber:string;supplierId:string;projectId?:string;totalAmount?:number|string;status?:string};
type Preview={record:any;lines:any[];number:string}|null;
type TxData={ok:boolean;supplierQuotes?:SupplierQuote[];purchaseOrders?:PurchaseOrder[];error?:string};
function localDate(){const d=new Date();const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Pacific/Port_Moresby",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}`;}
const money=(v:unknown)=>`K${Number(v||0).toFixed(2)}`;
const statusOf=(v:unknown)=>String(v||"").trim().toUpperCase();
const normalizeDocNo=(v:unknown)=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
const controlStyle={height:52,width:"100%"} as const;
const searchButtonStyle={height:44,width:"100%",marginTop:10} as const;

function SourcePreview({data}:{data:Preview}){if(!data)return null;const r=data.record;return <section className="panel"><div className="form-title-row"><h3>{data.number}</h3><span className="auto-badge">{r.status||"APPROVED"}</span></div><div className="document-meta"><div><span>Supplier</span><strong>{r.supplierId||"—"}</strong></div><div><span>Project</span><strong>{r.projectId||"—"}</strong></div><div><span>Date</span><strong>{r.poDate||"—"}</strong></div><div><span>Total</span><strong>{money(r.totalAmount)}</strong></div></div>{data.lines.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>UOM</th><th>Rate</th><th>Total</th></tr></thead><tbody>{data.lines.map((line:any,i:number)=><tr key={line.poLineId||i}><td>{line.lineNo||i+1}</td><td>{line.description||line.itemId||"—"}</td><td>{line.qty||0}</td><td>{line.uom||"—"}</td><td>{money(line.rate)}</td><td>{money(line.totalAmount||line.netAmount)}</td></tr>)}</tbody></table></div>}</section>}

export default function PurchaseConversionsPage(){
 const router=useRouter();
 const[supplierQuotes,setSupplierQuotes]=useState<SupplierQuote[]>([]),[purchaseOrders,setPurchaseOrders]=useState<PurchaseOrder[]>([]);
 const[selectedQuoteId,setSelectedQuoteId]=useState(""),[selectedPoId,setSelectedPoId]=useState("");
 const[quoteSearch,setQuoteSearch]=useState(""),[poSearch,setPoSearch]=useState("");
 const[quotePreview,setQuotePreview]=useState<Preview>(null),[poPreview,setPoPreview]=useState<Preview>(null);
 const[message,setMessage]=useState(""),[busy,setBusy]=useState(false);

 async function load(){try{const response=await fetch("/api/erp/transactions",{cache:"no-store"});const body=await response.json() as TxData;if(!response.ok||!body.ok)throw new Error(body.error||"Transaction load failed");setSupplierQuotes((body.supplierQuotes||[]).filter(r=>statusOf(r.status)==="APPROVED"));setPurchaseOrders((body.purchaseOrders||[]).filter(r=>["APPROVED","POSTED"].includes(statusOf(r.status))));}catch(error){setMessage(error instanceof Error?error.message:"Load failed");}}
 useEffect(()=>{void load();},[]);
 const selectedPo=useMemo(()=>purchaseOrders.find(r=>r.poId===selectedPoId),[purchaseOrders,selectedPoId]);

 async function preview(type:"supplierQuote"|"purchaseOrder",id:string,setter:(p:Preview)=>void){if(!id){setter(null);return;}setMessage("");const res=await fetch(`/api/erp/document-preview?type=${type}&id=${encodeURIComponent(id)}`,{cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok){setMessage(body.error||"Preview failed");setter(null);return;}setter({record:body.record,lines:body.lines||[],number:body.number});}
 function findSupplierQuote(query:string){const q=normalizeDocNo(query);if(!q)return null;return supplierQuotes.find(r=>normalizeDocNo(r.poNumber)===q||normalizeDocNo(r.poId)===q)||supplierQuotes.find(r=>normalizeDocNo(r.poNumber).includes(q)||normalizeDocNo(r.poId).includes(q))||null;}
 function findPurchaseOrder(query:string){const q=normalizeDocNo(query);if(!q)return null;return purchaseOrders.find(r=>normalizeDocNo(r.poNumber)===q||normalizeDocNo(r.poId)===q)||purchaseOrders.find(r=>normalizeDocNo(r.poNumber).includes(q)||normalizeDocNo(r.poId).includes(q))||null;}
 function searchSelectedSupplierQuote(){if(!selectedQuoteId){setQuotePreview(null);setMessage("Select an approved Supplier Quotation");return;}void preview("supplierQuote",selectedQuoteId,setQuotePreview);}
 function searchSelectedPurchaseOrder(){if(!selectedPoId){setPoPreview(null);setMessage("Select an approved / posted Purchase Order");return;}void preview("purchaseOrder",selectedPoId,setPoPreview);}
 function doSupplierQuoteSearch(){const match=findSupplierQuote(quoteSearch);if(!match){setQuotePreview(null);setMessage(quoteSearch.trim()?`Approved Supplier Quotation not found: ${quoteSearch}`:"Enter a supplier quotation number");return;}setSelectedQuoteId(match.poId);void preview("supplierQuote",match.poId,setQuotePreview);}
 function doPurchaseOrderSearch(){const match=findPurchaseOrder(poSearch);if(!match){setPoPreview(null);setMessage(poSearch.trim()?`Approved/Posted Purchase Order not found: ${poSearch}`:"Enter a purchase order number");return;}setSelectedPoId(match.poId);void preview("purchaseOrder",match.poId,setPoPreview);}

 async function supplierQuoteToPo(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!quotePreview||!selectedQuoteId)return;setBusy(true);setMessage("");try{const response=await fetch("/api/erp/purchase-conversions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierQuoteId:selectedQuoteId})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Conversion failed");router.push(`/transactions/purchaseOrder/${body.createdId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Conversion failed");}finally{setBusy(false);}}
 async function poToPayment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!poPreview||!selectedPoId)return;setBusy(true);setMessage("");try{const f=new FormData(event.currentTarget);const po=purchaseOrders.find(r=>r.poId===selectedPoId);if(!po)throw new Error("Select an approved Purchase Order");const amount=Number(f.get("amount")||0);if(!(amount>0))throw new Error("Payment amount must be greater than zero");const response=await fetch("/api/erp/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createPayment",payload:{paymentNumber:"",paymentType:"PAY",partyType:"Supplier",partyId:po.supplierId,projectId:po.projectId||"",paymentDate:f.get("paymentDate"),amount,paymentMethod:f.get("paymentMethod"),cashBankAccountId:f.get("cashBankAccountId"),againstDocumentType:"Purchase Order",againstDocumentId:po.poId,reference:f.get("reference")||""}})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Purchase payment creation failed");router.push(`/transactions/payment/${body.result.recordId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Purchase payment creation failed");}finally{setBusy(false);}}

 return <><div className="page-heading"><div><h2>Purchase Document Conversions</h2><p className="small">Select from the dropdown and press Search, or enter a document number manually and press Search.</p></div></div>{message&&<section className="panel"><strong>Status:</strong> {message}</section>}
 <form className="panel form-grid" onSubmit={supplierQuoteToPo}><h3 className="form-title">Supplier Quotation → Purchase Order</h3><label>Approved Supplier Quotation<select style={controlStyle} value={selectedQuoteId} onChange={e=>{setSelectedQuoteId(e.target.value);setQuotePreview(null);}}><option value="">Select quotation document no ({supplierQuotes.length})</option>{supplierQuotes.map(q=><option key={q.poId} value={q.poId}>{q.poNumber||q.poId}</option>)}</select><button style={searchButtonStyle} type="button" onClick={searchSelectedSupplierQuote}>Search</button></label><label>Manual Search by Quotation No<input style={controlStyle} placeholder="e.g. SUPQ-2026-00001" value={quoteSearch} onChange={e=>setQuoteSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();doSupplierQuoteSearch();}}}/><button style={searchButtonStyle} type="button" onClick={doSupplierQuoteSearch}>Search</button></label><div className="form-wide"><SourcePreview data={quotePreview}/></div>{quotePreview&&<div className="form-wide"><button type="submit" disabled={busy}>Convert to Purchase Order</button></div>}</form>
 <form className="panel form-grid" onSubmit={poToPayment}><h3 className="form-title">Purchase Order → Purchase Payment / Receipt</h3><label>Approved / Posted Purchase Order<select style={controlStyle} value={selectedPoId} onChange={e=>{setSelectedPoId(e.target.value);setPoPreview(null);}}><option value="">Select purchase order document no ({purchaseOrders.length})</option>{purchaseOrders.map(po=><option key={po.poId} value={po.poId}>{po.poNumber||po.poId}</option>)}</select><button style={searchButtonStyle} type="button" onClick={searchSelectedPurchaseOrder}>Search</button></label><label>Manual Search by PO No<input style={controlStyle} placeholder="e.g. PO-2026-00001" value={poSearch} onChange={e=>setPoSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();doPurchaseOrderSearch();}}}/><button style={searchButtonStyle} type="button" onClick={doPurchaseOrderSearch}>Search</button></label><div className="form-wide"><SourcePreview data={poPreview}/></div>{poPreview&&<><label>Payment Date<input name="paymentDate" type="date" required defaultValue={localDate()}/></label><label>Amount<input key={selectedPoId} name="amount" type="number" min="0.01" step="0.01" required defaultValue={Number(selectedPo?.totalAmount||0)}/></label><label>Method<select name="paymentMethod" defaultValue="Bank Transfer"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option></select></label><label>Cash / Bank Account<input name="cashBankAccountId" defaultValue="ACC-1110" required/></label><label className="form-wide">Reference<input name="reference" placeholder="Bank ref / supplier payment ref"/></label><div className="form-wide"><button type="submit" disabled={busy}>Convert to Purchase Payment / Receipt</button></div></>}</form></>;
}
