"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Quote={quoteId:string;quoteNumber:string;customerId:string;projectId?:string;totalAmount?:number|string;status?:string};
type Invoice={invoiceId:string;invoiceNumber:string;customerId:string;projectId?:string;totalAmount?:number|string;outstandingAmount?:number|string;status?:string};
type Preview={record:any;lines:any[];number:string}|null;
type TxData={ok:boolean;quotes?:Quote[];invoices?:Invoice[];error?:string};

function localDate(plusDays=0){const d=new Date();d.setDate(d.getDate()+plusDays);const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Pacific/Port_Moresby",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}`;}
const money=(v:unknown)=>`K${Number(v||0).toFixed(2)}`;
const statusOf=(v:unknown)=>String(v||"").trim().toUpperCase();
const normalizeDocNo=(v:unknown)=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
const controlStyle={height:48,width:"100%"} as const;
const searchRowStyle={display:"grid",gridTemplateColumns:"minmax(0,1fr) 110px",gap:10,alignItems:"stretch"} as const;

function SourcePreview({data}:{data:Preview}){if(!data)return null;const r=data.record;return <section className="panel"><div className="form-title-row"><h3>{data.number}</h3><span className="auto-badge">{r.status||"APPROVED"}</span></div><div className="document-meta"><div><span>Customer</span><strong>{r.customerId||"—"}</strong></div><div><span>Project</span><strong>{r.projectId||"—"}</strong></div><div><span>Date</span><strong>{r.quoteDate||r.invoiceDate||"—"}</strong></div><div><span>Total</span><strong>{money(r.totalAmount)}</strong></div>{r.outstandingAmount!==undefined&&<div><span>Outstanding</span><strong>{money(r.outstandingAmount)}</strong></div>}</div>{data.lines.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>UOM</th><th>Rate</th><th>Total</th></tr></thead><tbody>{data.lines.map((line:any,i:number)=><tr key={line.invoiceLineId||line.quoteLineId||i}><td>{line.lineNo||i+1}</td><td>{line.description||line.itemId||"—"}</td><td>{line.qty||0}</td><td>{line.uom||"—"}</td><td>{money(line.rate)}</td><td>{money(line.totalAmount||line.netAmount)}</td></tr>)}</tbody></table></div>}</section>}

export default function SalesConversionsPage(){
 const router=useRouter();
 const[quotes,setQuotes]=useState<Quote[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]);
 const[selectedQuoteId,setSelectedQuoteId]=useState(""),[selectedInvoiceId,setSelectedInvoiceId]=useState("");
 const[quoteSearch,setQuoteSearch]=useState(""),[invoiceSearch,setInvoiceSearch]=useState("");
 const[quotePreview,setQuotePreview]=useState<Preview>(null),[invoicePreview,setInvoicePreview]=useState<Preview>(null);
 const[message,setMessage]=useState(""),[busy,setBusy]=useState(false);

 async function load(){try{const response=await fetch("/api/erp/transactions",{cache:"no-store"});const body=await response.json() as TxData;if(!response.ok||!body.ok)throw new Error(body.error||"Transaction load failed");setQuotes((body.quotes||[]).filter(r=>statusOf(r.status)==="APPROVED"));setInvoices((body.invoices||[]).filter(r=>["APPROVED","POSTED"].includes(statusOf(r.status))&&Number(r.outstandingAmount??r.totalAmount??0)>0));}catch(error){setMessage(error instanceof Error?error.message:"Load failed");}}
 useEffect(()=>{void load();},[]);
 const selectedInvoice=useMemo(()=>invoices.find(r=>r.invoiceId===selectedInvoiceId),[invoices,selectedInvoiceId]);

 async function preview(type:"quote"|"invoice",id:string,setter:(p:Preview)=>void){if(!id){setter(null);return;}setMessage("");const res=await fetch(`/api/erp/document-preview?type=${type}&id=${encodeURIComponent(id)}`,{cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok){setMessage(body.error||"Preview failed");setter(null);return;}setter({record:body.record,lines:body.lines||[],number:body.number});}
 function selectQuote(id:string){setSelectedQuoteId(id);setQuotePreview(null);if(id)void preview("quote",id,setQuotePreview);}
 function selectInvoice(id:string){setSelectedInvoiceId(id);setInvoicePreview(null);if(id)void preview("invoice",id,setInvoicePreview);}
 function findQuote(query:string){const q=normalizeDocNo(query);if(!q)return null;return quotes.find(r=>normalizeDocNo(r.quoteNumber)===q||normalizeDocNo(r.quoteId)===q)||quotes.find(r=>normalizeDocNo(r.quoteNumber).includes(q)||normalizeDocNo(r.quoteId).includes(q))||null;}
 function findInvoice(query:string){const q=normalizeDocNo(query);if(!q)return null;return invoices.find(r=>normalizeDocNo(r.invoiceNumber)===q||normalizeDocNo(r.invoiceId)===q)||invoices.find(r=>normalizeDocNo(r.invoiceNumber).includes(q)||normalizeDocNo(r.invoiceId).includes(q))||null;}
 function doQuoteSearch(){const match=findQuote(quoteSearch);if(!match){setSelectedQuoteId("");setQuotePreview(null);setMessage(quoteSearch.trim()?`Approved Sales Quotation not found: ${quoteSearch}`:"Enter a quotation number");return;}setSelectedQuoteId(match.quoteId);void preview("quote",match.quoteId,setQuotePreview);}
 function doInvoiceSearch(){const match=findInvoice(invoiceSearch);if(!match){setSelectedInvoiceId("");setInvoicePreview(null);setMessage(invoiceSearch.trim()?`Approved/Posted Sales Invoice not found: ${invoiceSearch}`:"Enter an invoice number");return;}setSelectedInvoiceId(match.invoiceId);void preview("invoice",match.invoiceId,setInvoicePreview);}

 async function quoteToInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!quotePreview||!selectedQuoteId)return;setBusy(true);setMessage("");try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch("/api/erp/conversions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"quoteToInvoice",payload})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Conversion failed");router.push(`/transactions/invoice/${body.createdId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Conversion failed");}finally{setBusy(false);}}
 async function invoiceToReceipt(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!invoicePreview||!selectedInvoiceId)return;setBusy(true);setMessage("");try{const f=new FormData(event.currentTarget);const invoice=invoices.find(r=>r.invoiceId===selectedInvoiceId);if(!invoice)throw new Error("Select an approved Sales Invoice");const amount=Number(f.get("amount")||0);if(!(amount>0))throw new Error("Receipt amount must be greater than zero");const response=await fetch("/api/erp/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createPayment",payload:{paymentNumber:"",paymentType:"RECEIVE",partyType:"Customer",partyId:invoice.customerId,projectId:invoice.projectId||"",paymentDate:f.get("paymentDate"),amount,paymentMethod:f.get("paymentMethod"),cashBankAccountId:f.get("cashBankAccountId"),againstDocumentType:"Sales Invoice",againstDocumentId:invoice.invoiceId,reference:f.get("reference")||""}})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Receipt creation failed");router.push(`/transactions/payment/${body.result.recordId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Receipt creation failed");}finally{setBusy(false);}}

 return <><div className="page-heading"><div><h2>Sales Document Conversions</h2><p className="small">Select an approved document from the dropdown OR enter the document number manually and click Search.</p></div></div>{message&&<section className="panel"><strong>Status:</strong> {message}</section>}
 <form className="panel form-grid" onSubmit={quoteToInvoice}><h3 className="form-title">Sales Quotation → Sales Invoice</h3><label>Approved Sales Quotation<select style={controlStyle} value={selectedQuoteId} onChange={e=>selectQuote(e.target.value)}><option value="">Select quotation document no ({quotes.length})</option>{quotes.map(q=><option key={q.quoteId} value={q.quoteId}>{q.quoteNumber||q.quoteId}</option>)}</select></label><label>Manual Search by Quotation No<div style={searchRowStyle}><input style={controlStyle} placeholder="e.g. SQ-2026-00001" value={quoteSearch} onChange={e=>setQuoteSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();doQuoteSearch();}}}/><button style={controlStyle} type="button" onClick={doQuoteSearch}>Search</button></div></label><input type="hidden" name="quoteId" value={selectedQuoteId}/><div className="form-wide"><SourcePreview data={quotePreview}/></div>{quotePreview&&<><label>Invoice Date<input name="invoiceDate" type="date" required defaultValue={localDate()}/></label><label>Due Date<input name="dueDate" type="date" defaultValue={localDate(30)}/></label><label>Revenue Account<input name="revenueAccountId" defaultValue="ACC-4100"/></label><div className="form-wide"><button type="submit" disabled={busy}>Convert to Sales Invoice</button></div></>}</form>
 <form className="panel form-grid" onSubmit={invoiceToReceipt}><h3 className="form-title">Sales Invoice → Sales Payment Entry / Receipt</h3><label>Approved / Posted Sales Invoice<select style={controlStyle} value={selectedInvoiceId} onChange={e=>selectInvoice(e.target.value)}><option value="">Select invoice document no ({invoices.length})</option>{invoices.map(inv=><option key={inv.invoiceId} value={inv.invoiceId}>{inv.invoiceNumber||inv.invoiceId}</option>)}</select></label><label>Manual Search by Invoice No<div style={searchRowStyle}><input style={controlStyle} placeholder="e.g. SI-2026-00001" value={invoiceSearch} onChange={e=>setInvoiceSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();doInvoiceSearch();}}}/><button style={controlStyle} type="button" onClick={doInvoiceSearch}>Search</button></div></label><div className="form-wide"><SourcePreview data={invoicePreview}/></div>{invoicePreview&&<><label>Receipt Date<input name="paymentDate" type="date" required defaultValue={localDate()}/></label><label>Amount<input key={selectedInvoiceId} name="amount" type="number" min="0.01" step="0.01" required defaultValue={Number(selectedInvoice?.outstandingAmount??selectedInvoice?.totalAmount??0)}/></label><label>Method<select name="paymentMethod" defaultValue="Bank Transfer"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option></select></label><label>Cash / Bank Account<input name="cashBankAccountId" defaultValue="ACC-1110" required/></label><label className="form-wide">Reference<input name="reference" placeholder="Bank ref / receipt ref"/></label><div className="form-wide"><button type="submit" disabled={busy}>Convert to Sales Payment Entry / Receipt</button></div></>}</form></>;
}
