"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Quote={quoteId:string;quoteNumber:string;customerId:string;projectId?:string;totalAmount?:number|string;status?:string};
type Invoice={invoiceId:string;invoiceNumber:string;customerId:string;projectId?:string;totalAmount?:number|string;outstandingAmount?:number|string;status?:string};
type Preview={record:any;lines:any[];number:string}|null;
type TxData={ok:boolean;quotes?:Quote[];invoices?:Invoice[];error?:string};

function localDate(plusDays=0){const d=new Date();d.setDate(d.getDate()+plusDays);const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Pacific/Port_Moresby",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}`;}
const money=(v:unknown)=>`K${Number(v||0).toFixed(2)}`;

function SourcePreview({data}:{data:Preview}){if(!data)return null;const r=data.record;return <section className="panel"><div className="form-title-row"><h3>{data.number}</h3><span className="auto-badge">{r.status||"APPROVED"}</span></div><div className="document-meta"><div><span>Customer</span><strong>{r.customerId||"—"}</strong></div><div><span>Project</span><strong>{r.projectId||"—"}</strong></div><div><span>Date</span><strong>{r.quoteDate||r.invoiceDate||"—"}</strong></div><div><span>Total</span><strong>{money(r.totalAmount)}</strong></div>{r.outstandingAmount!==undefined&&<div><span>Outstanding</span><strong>{money(r.outstandingAmount)}</strong></div>}</div>{data.lines.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>UOM</th><th>Rate</th><th>Total</th></tr></thead><tbody>{data.lines.map((line:any,i:number)=><tr key={line.invoiceLineId||line.quoteLineId||i}><td>{line.lineNo||i+1}</td><td>{line.description||line.itemId||"—"}</td><td>{line.qty||0}</td><td>{line.uom||"—"}</td><td>{money(line.rate)}</td><td>{money(line.totalAmount||line.netAmount)}</td></tr>)}</tbody></table></div>}</section>}

export default function SalesConversionsPage(){
 const router=useRouter();const[quotes,setQuotes]=useState<Quote[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[selectedQuoteId,setSelectedQuoteId]=useState("");const[selectedInvoiceId,setSelectedInvoiceId]=useState("");const[quotePreview,setQuotePreview]=useState<Preview>(null);const[invoicePreview,setInvoicePreview]=useState<Preview>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function load(){try{const response=await fetch("/api/erp/transactions");const body=await response.json() as TxData;if(!response.ok||!body.ok)throw new Error(body.error||"Transaction load failed");setQuotes((body.quotes||[]).filter(r=>String(r.status||"").toUpperCase()==="APPROVED"));setInvoices((body.invoices||[]).filter(r=>String(r.status||"").toUpperCase()==="APPROVED"&&Number(r.outstandingAmount??r.totalAmount??0)>0));}catch(error){setMessage(error instanceof Error?error.message:"Load failed");}}
 useEffect(()=>{void load();},[]);
 const selectedInvoice=useMemo(()=>invoices.find(r=>r.invoiceId===selectedInvoiceId),[invoices,selectedInvoiceId]);
 async function preview(type:"quote"|"invoice",id:string,setter:(p:Preview)=>void){if(!id){setter(null);return;}const res=await fetch(`/api/erp/document-preview?type=${type}&id=${encodeURIComponent(id)}`);const body=await res.json();if(!res.ok||!body.ok){setMessage(body.error||"Preview failed");setter(null);return;}setter({record:body.record,lines:body.lines||[],number:body.number});}
 async function quoteToInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!quotePreview)return;setBusy(true);setMessage("");try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch("/api/erp/conversions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"quoteToInvoice",payload})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Conversion failed");router.push(`/transactions/invoice/${body.createdId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Conversion failed");}finally{setBusy(false);}}
 async function invoiceToReceipt(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!invoicePreview)return;setBusy(true);setMessage("");try{const f=new FormData(event.currentTarget);const invoice=invoices.find(r=>r.invoiceId===selectedInvoiceId);if(!invoice)throw new Error("Select an approved Sales Invoice");const amount=Number(f.get("amount")||0);if(!(amount>0))throw new Error("Receipt amount must be greater than zero");const response=await fetch("/api/erp/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createPayment",payload:{paymentNumber:"",paymentType:"RECEIVE",partyType:"Customer",partyId:invoice.customerId,projectId:invoice.projectId||"",paymentDate:f.get("paymentDate"),amount,paymentMethod:f.get("paymentMethod"),cashBankAccountId:f.get("cashBankAccountId"),againstDocumentType:"Sales Invoice",againstDocumentId:invoice.invoiceId,reference:f.get("reference")||""}})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||"Receipt creation failed");router.push(`/transactions/payment/${body.result.recordId}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Receipt creation failed");}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h2>Sales Document Conversions</h2><p className="small">Search/select an approved source document, review the full document, then convert it.</p></div></div>{message&&<section className="panel"><strong>Status:</strong> {message}</section>}
 <form className="panel form-grid" onSubmit={quoteToInvoice}><h3 className="form-title">Sales Quotation → Sales Invoice</h3><label>Approved Sales Quotation<input list="approved-sales-quotations" placeholder="Search by quotation no" value={selectedQuoteId} onChange={e=>{const value=e.target.value;const match=quotes.find(q=>q.quoteId===value||q.quoteNumber===value);const id=match?.quoteId||value;setSelectedQuoteId(id);void preview("quote",id,setQuotePreview);}} required/><datalist id="approved-sales-quotations">{quotes.map(q=><option key={q.quoteId} value={q.quoteId}>{q.quoteNumber} · {q.customerId} · {money(q.totalAmount)}</option>)}</datalist><input type="hidden" name="quoteId" value={selectedQuoteId}/></label><div className="form-wide"><SourcePreview data={quotePreview}/></div>{quotePreview&&<><label>Invoice Date<input name="invoiceDate" type="date" required defaultValue={localDate()}/></label><label>Due Date<input name="dueDate" type="date" defaultValue={localDate(30)}/></label><label>Revenue Account<input name="revenueAccountId" defaultValue="ACC-4100"/></label><div className="form-wide"><button type="submit" disabled={busy}>Convert to Sales Invoice</button></div></>}</form>
 <form className="panel form-grid" onSubmit={invoiceToReceipt}><h3 className="form-title">Sales Invoice → Sales Payment Entry / Receipt</h3><label>Approved Sales Invoice<input list="approved-sales-invoices" placeholder="Search by invoice no" value={selectedInvoiceId} onChange={e=>{const value=e.target.value;const match=invoices.find(i=>i.invoiceId===value||i.invoiceNumber===value);const id=match?.invoiceId||value;setSelectedInvoiceId(id);void preview("invoice",id,setInvoicePreview);}} required/><datalist id="approved-sales-invoices">{invoices.map(inv=><option key={inv.invoiceId} value={inv.invoiceId}>{inv.invoiceNumber} · {inv.customerId} · Outstanding {money(inv.outstandingAmount??inv.totalAmount)}</option>)}</datalist></label><div className="form-wide"><SourcePreview data={invoicePreview}/></div>{invoicePreview&&<><label>Receipt Date<input name="paymentDate" type="date" required defaultValue={localDate()}/></label><label>Amount<input key={selectedInvoiceId} name="amount" type="number" min="0.01" step="0.01" required defaultValue={Number(selectedInvoice?.outstandingAmount??selectedInvoice?.totalAmount??0)}/></label><label>Method<select name="paymentMethod" defaultValue="Bank Transfer"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option></select></label><label>Cash / Bank Account<input name="cashBankAccountId" defaultValue="ACC-1110" required/></label><label className="form-wide">Reference<input name="reference" placeholder="Bank ref / receipt ref"/></label><div className="form-wide"><button type="submit" disabled={busy}>Convert to Sales Payment Entry / Receipt</button></div></>}</form></>;
}
