import Link from "next/link";
import { notFound } from "next/navigation";
import { findRecords } from "@/lib/backend/apps-script";
import { requirePermission, type Permission } from "@/lib/auth";
import PrintButton from "@/app/components/print-button";
import DocumentConversionActions from "@/app/components/document-conversion-actions";
import DocumentWorkflowActions from "@/app/components/document-workflow-actions";

const CONFIG: Record<string,{table:string;idField:string;numberField:string;lineTable?:string;lineIdField?:string;permission:Permission;title:string}>={
 quote:{table:"Quotes",idField:"quoteId",numberField:"quoteNumber",lineTable:"QuoteLines",lineIdField:"quoteId",permission:"sales.read",title:"Sales Quotation"},
 invoice:{table:"Invoices",idField:"invoiceId",numberField:"invoiceNumber",lineTable:"InvoiceLines",lineIdField:"invoiceId",permission:"sales.read",title:"Sales Invoice"},
 purchaseOrder:{table:"PurchaseOrders",idField:"poId",numberField:"poNumber",lineTable:"POLines",lineIdField:"poId",permission:"purchase.read",title:"Purchase Order"},
 supplierBill:{table:"SupplierBills",idField:"billId",numberField:"billNumber",lineTable:"SupplierBillLines",lineIdField:"billId",permission:"purchase.read",title:"Supplier Bill"},
 payment:{table:"Payments",idField:"paymentId",numberField:"paymentNumber",permission:"dashboard.read",title:"Payment / Receipt"},
 expense:{table:"Expenses",idField:"expenseId",numberField:"expenseNumber",permission:"purchase.read",title:"Expense"},
};
const labels:Record<string,string>={customerId:"Customer",supplierId:"Supplier",projectId:"Project",quoteDate:"Date",invoiceDate:"Date",poDate:"Date",billDate:"Date",paymentDate:"Date",expenseDate:"Date",dueDate:"Due Date",expiryDate:"Valid Till",netAmount:"Net Amount",gstAmount:"GST",totalAmount:"Total",paidAmount:"Paid",outstandingAmount:"Outstanding",status:"Status",reference:"Reference",paymentMethod:"Payment Method",description:"Description",journalId:"Journal",sourceDocumentId:"Source Document"};const moneyFields=new Set(["netAmount","gstAmount","totalAmount","paidAmount","outstandingAmount","amount"]);function display(key:string,value:unknown){if(moneyFields.has(key))return `K${Number(value||0).toFixed(2)}`;return String(value??"")}

export default async function TransactionDocumentPage({params}:{params:Promise<{type:string;id:string}>}){const{type,id}=await params;const config=CONFIG[type];if(!config)notFound();await requirePermission(config.permission);const result=await findRecords<any>(config.table,{[config.idField]:id},1);const record=result.rows[0];if(!record)notFound();if(type==="payment"){if(String(record.partyType)==="Customer")await requirePermission("sales.read");else if(String(record.partyType)==="Supplier")await requirePermission("purchase.read");else await requirePermission("accounts.read")}
 const lines=config.lineTable&&config.lineIdField?(await findRecords<any>(config.lineTable,{[config.lineIdField]:id},500)).rows:[];const number=String(record[config.numberField]||id);let title=config.title;let module="accounts";if(type==="quote"||type==="invoice")module="sales";if(type==="purchaseOrder"||type==="supplierBill"||type==="expense")module="purchase";if(type==="purchaseOrder"&&number.startsWith("SUPQ-"))title="Supplier Quotation";if(type==="payment"){if(String(record.partyType)==="Customer"){title="Sales Payment Entry / Receipt";module="sales"}else if(String(record.partyType)==="Supplier"){title="Purchase Payment / Receipt";module="purchase"}}
 const hidden=new Set([config.idField,config.numberField,"createdAt","updatedAt"]);const fields=Object.entries(record).filter(([key,value])=>!hidden.has(key)&&value!==""&&value!==null&&value!==undefined);
 return <div className="document-page"><div className="document-toolbar no-print"><Link href={`/transactions?module=${module}`}>← {module==="sales"?"Sales Transactions":module==="purchase"?"Purchase Transactions":"Transactions"}</Link><div className="row-actions"><PrintButton/></div></div><section className="document-sheet"><header className="document-header"><div><div className="eyebrow">EASYNET IT SOLUTIONS LIMITED</div><h1>{title}</h1><div className="document-number">{number}</div></div><div className={`status-pill status-${String(record.status||"draft").toLowerCase()}`}>{record.status||"DRAFT"}</div></header><div className="document-meta">{fields.map(([key,value])=><div key={key}><span>{labels[key]||key.replace(/([A-Z])/g," $1")}</span><strong>{display(key,value)}</strong></div>)}</div>{lines.length>0&&<div className="document-lines"><table className="data-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>UOM</th><th>Rate</th><th>Net</th><th>GST</th><th>Total</th></tr></thead><tbody>{lines.map((line:any,index:number)=><tr key={line.invoiceLineId||line.quoteLineId||line.poLineId||line.billLineId||index}><td>{line.lineNo||index+1}</td><td>{line.description}{line.itemId?<><br/><span className="small">{line.itemId}</span></>:null}</td><td>{line.qty}</td><td>{line.uom}</td><td>K{Number(line.rate||0).toFixed(2)}</td><td>K{Number(line.netAmount||0).toFixed(2)}</td><td>K{Number(line.gstAmount||0).toFixed(2)}</td><td><strong>K{Number(line.totalAmount||0).toFixed(2)}</strong></td></tr>)}</tbody></table></div>}<div className="document-footer"><span>System generated document</span><span>Record ID: {id}</span></div></section><DocumentWorkflowActions recordType={type as "quote"|"invoice"|"purchaseOrder"|"supplierBill"|"payment"|"expense"} recordId={id} status={String(record.status||"DRAFT")}/><DocumentConversionActions type={type} id={id} status={String(record.status||"")} documentNumber={number}/></div>;
}
