export const INITIAL_CHART_OF_ACCOUNTS = [
  // Assets
  { accountId: "ACC-1000", accountCode: "1000", accountName: "Assets", accountType: "Asset", parentAccount: "", active: true },
  { accountId: "ACC-1100", accountCode: "1100", accountName: "Current Assets", accountType: "Asset", parentAccount: "ACC-1000", active: true },
  { accountId: "ACC-1110", accountCode: "1110", accountName: "Cash on Hand", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1120", accountCode: "1120", accountName: "Operating Bank Account", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1121", accountCode: "1121", accountName: "Savings / Reserve Bank Account", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1130", accountCode: "1130", accountName: "Accounts Receivable", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1140", accountCode: "1140", accountName: "GST Receivable / Input GST", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1150", accountCode: "1150", accountName: "Inventory / Project Materials", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1160", accountCode: "1160", accountName: "Supplier Advances", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1170", accountCode: "1170", accountName: "Prepaid Expenses", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1180", accountCode: "1180", accountName: "Employee / Staff Advances", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1190", accountCode: "1190", accountName: "Other Current Assets", accountType: "Asset", parentAccount: "ACC-1100", active: true },
  { accountId: "ACC-1200", accountCode: "1200", accountName: "Non-Current Assets", accountType: "Asset", parentAccount: "ACC-1000", active: true },
  { accountId: "ACC-1210", accountCode: "1210", accountName: "Computer & ICT Equipment", accountType: "Asset", parentAccount: "ACC-1200", active: true },
  { accountId: "ACC-1220", accountCode: "1220", accountName: "Office Equipment", accountType: "Asset", parentAccount: "ACC-1200", active: true },
  { accountId: "ACC-1230", accountCode: "1230", accountName: "Furniture & Fixtures", accountType: "Asset", parentAccount: "ACC-1200", active: true },
  { accountId: "ACC-1240", accountCode: "1240", accountName: "Motor Vehicles", accountType: "Asset", parentAccount: "ACC-1200", active: true },
  { accountId: "ACC-1290", accountCode: "1290", accountName: "Accumulated Depreciation", accountType: "Contra Asset", parentAccount: "ACC-1200", active: true },

  // Liabilities
  { accountId: "ACC-2000", accountCode: "2000", accountName: "Liabilities", accountType: "Liability", parentAccount: "", active: true },
  { accountId: "ACC-2100", accountCode: "2100", accountName: "Current Liabilities", accountType: "Liability", parentAccount: "ACC-2000", active: true },
  { accountId: "ACC-2110", accountCode: "2110", accountName: "Accounts Payable", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2120", accountCode: "2120", accountName: "GST Payable / Output GST", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2130", accountCode: "2130", accountName: "Current Loan Payable", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2140", accountCode: "2140", accountName: "Accrued Interest Payable", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2150", accountCode: "2150", accountName: "Customer Advances / Unearned Revenue", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2160", accountCode: "2160", accountName: "Accrued Expenses", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2170", accountCode: "2170", accountName: "Payroll & Staff Deductions Payable", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2180", accountCode: "2180", accountName: "Other Current Liabilities", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2190", accountCode: "2190", accountName: "Stock Received But Not Billed / GRNI", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2191", accountCode: "2191", accountName: "Landed Cost Clearing", accountType: "Liability", parentAccount: "ACC-2100", active: true },
  { accountId: "ACC-2200", accountCode: "2200", accountName: "Non-Current Liabilities", accountType: "Liability", parentAccount: "ACC-2000", active: true },
  { accountId: "ACC-2210", accountCode: "2210", accountName: "Long-Term Borrowings", accountType: "Liability", parentAccount: "ACC-2200", active: true },

  // Equity
  { accountId: "ACC-3000", accountCode: "3000", accountName: "Equity", accountType: "Equity", parentAccount: "", active: true },
  { accountId: "ACC-3100", accountCode: "3100", accountName: "Share Capital", accountType: "Equity", parentAccount: "ACC-3000", active: true },
  { accountId: "ACC-3200", accountCode: "3200", accountName: "Retained Earnings", accountType: "Equity", parentAccount: "ACC-3000", active: true },
  { accountId: "ACC-3300", accountCode: "3300", accountName: "Current Year Earnings", accountType: "Equity", parentAccount: "ACC-3000", active: true },
  { accountId: "ACC-3400", accountCode: "3400", accountName: "Shareholder / Director Contributions", accountType: "Equity", parentAccount: "ACC-3000", active: true },

  // Revenue
  { accountId: "ACC-4000", accountCode: "4000", accountName: "Revenue", accountType: "Income", parentAccount: "", active: true },
  { accountId: "ACC-4100", accountCode: "4100", accountName: "ICT Infrastructure Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4200", accountCode: "4200", accountName: "Hardware Sales Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4300", accountCode: "4300", accountName: "Software & Digital Solutions Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4400", accountCode: "4400", accountName: "Managed IT Services Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4500", accountCode: "4500", accountName: "Business Automation / ERP Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4600", accountCode: "4600", accountName: "Consulting & Technical Support Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4700", accountCode: "4700", accountName: "Cloud / Hosting / Subscription Revenue", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4900", accountCode: "4900", accountName: "Other Income", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4910", accountCode: "4910", accountName: "Inventory Adjustment / Revaluation Gain", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4920", accountCode: "4920", accountName: "Realized Foreign Exchange Gain", accountType: "Income", parentAccount: "ACC-4000", active: true },
  { accountId: "ACC-4930", accountCode: "4930", accountName: "Unrealized Foreign Exchange Gain", accountType: "Income", parentAccount: "ACC-4000", active: true },

  // Cost of Sales / Direct Costs
  { accountId: "ACC-5000", accountCode: "5000", accountName: "Cost of Sales", accountType: "Expense", parentAccount: "", active: true },
  { accountId: "ACC-5100", accountCode: "5100", accountName: "Hardware & Materials Cost", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5110", accountCode: "5110", accountName: "Purchase Price Variance", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5120", accountCode: "5120", accountName: "Inventory Adjustment / NRV Write-down", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5200", accountCode: "5200", accountName: "Project Direct Costs", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5300", accountCode: "5300", accountName: "Subcontractor / Consultant Cost", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5400", accountCode: "5400", accountName: "Software / Licence Cost of Sales", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5500", accountCode: "5500", accountName: "Freight & Delivery Cost", accountType: "Expense", parentAccount: "ACC-5000", active: true },
  { accountId: "ACC-5600", accountCode: "5600", accountName: "Cloud / Hosting Direct Cost", accountType: "Expense", parentAccount: "ACC-5000", active: true },

  // Operating Expenses
  { accountId: "ACC-6000", accountCode: "6000", accountName: "Operating Expenses", accountType: "Expense", parentAccount: "", active: true },
  { accountId: "ACC-6100", accountCode: "6100", accountName: "Interest Expense", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6200", accountCode: "6200", accountName: "Internet & Communications", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6300", accountCode: "6300", accountName: "Transport & Travel", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6400", accountCode: "6400", accountName: "Marketing & Advertising", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6500", accountCode: "6500", accountName: "Software & Subscriptions", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6600", accountCode: "6600", accountName: "Office & Administration", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6610", accountCode: "6610", accountName: "Rent & Premises", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6620", accountCode: "6620", accountName: "Printing & Stationery", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6700", accountCode: "6700", accountName: "Repairs & Maintenance", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6800", accountCode: "6800", accountName: "Depreciation Expense", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6900", accountCode: "6900", accountName: "Bank Fees & Charges", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6910", accountCode: "6910", accountName: "Professional & Legal Fees", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6920", accountCode: "6920", accountName: "Insurance", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6930", accountCode: "6930", accountName: "Utilities", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6940", accountCode: "6940", accountName: "Salaries & Wages", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6950", accountCode: "6950", accountName: "Staff Benefits & Welfare", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6960", accountCode: "6960", accountName: "Training & Development", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6970", accountCode: "6970", accountName: "Licences, Registrations & Compliance", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6980", accountCode: "6980", accountName: "Bad Debts / Impairment", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6990", accountCode: "6990", accountName: "Other Operating Expenses", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6995", accountCode: "6995", accountName: "Realized Foreign Exchange Loss", accountType: "Expense", parentAccount: "ACC-6000", active: true },
  { accountId: "ACC-6996", accountCode: "6996", accountName: "Unrealized Foreign Exchange Loss", accountType: "Expense", parentAccount: "ACC-6000", active: true },
] as const;

export const INITIAL_ACCOUNT_IDS = {
  cash: "ACC-1110",
  bank: "ACC-1120",
  accountsReceivable: "ACC-1130",
  inputGst: "ACC-1140",
  inventory: "ACC-1150",
  supplierAdvances: "ACC-1160",
  accountsPayable: "ACC-2110",
  gstPayable: "ACC-2120",
  loanPayable: "ACC-2130",
  accruedInterestPayable: "ACC-2140",
  customerAdvances: "ACC-2150",
  grni: "ACC-2190",
  landedCostClearing: "ACC-2191",
  inventoryRevaluationGain: "ACC-4910",
  exchangeGain: "ACC-4920",
  exchangeUnrealizedGain: "ACC-4930",
  purchasePriceVariance: "ACC-5110",
  inventoryAdjustmentLoss: "ACC-5120",
  interestExpense: "ACC-6100",
  exchangeLoss: "ACC-6995",
  exchangeUnrealizedLoss: "ACC-6996",
} as const;
