"use client";

import { FormEvent, useEffect, useState } from "react";
type Setting={key:string;value:string;notes:string};
export default function SettingsPage(){
 const [settings,setSettings]=useState<Setting[]>([]);const [message,setMessage]=useState("");
 async function load(){try{const r=await fetch("/api/settings");const b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Settings load failed");setSettings(b.settings||[])}catch(e){setMessage(e instanceof Error?e.message:"Settings load failed")}}
 useEffect(()=>{void load()},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const r=await fetch("/api/erp/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target:"settings",body:{setting:{key:form.get("key"),value:form.get("value"),notes:form.get("notes")}}})});const b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Save failed");setMessage(`${b.row.key} ${b.action}.`);event.currentTarget.reset();await load()}catch(e){setMessage(e instanceof Error?e.message:"Save failed")}}
 const value=(key:string)=>settings.find(row=>row.key===key)?.value||"";
 return <><h2>Finance Settings</h2><p className="small">Controlled configuration. Only users with Settings permission can update values.</p><div className="grid"><div className="card"><div className="label">Company</div><div className="value small-value">{value("company_name")||"—"}</div></div><div className="card"><div className="label">Base Currency</div><div className="value">{value("base_currency")||"—"}</div></div><div className="card"><div className="label">GST Status</div><div className="value small-value">{value("gst_status")||"UNVERIFIED"}</div></div><div className="card"><div className="label">GST Number</div><div className="value small-value">{value("gst_number")||"—"}</div></div></div>{message&&<section className="panel"><strong>Status:</strong> {message}</section>}<form className="panel form-grid" onSubmit={save}><h3 className="form-title">Update Setting</h3><label>Setting<select name="key" required defaultValue="gst_status"><option value="company_name">Company Name</option><option value="base_currency">Base Currency</option><option value="financial_year_start_month">Financial Year Start Month</option><option value="gst_status">GST Status</option><option value="gst_number">GST Number</option><option value="company_bank_name">Company Bank Name</option><option value="company_bank_account">Company Bank Account</option><option value="company_bank_bsb">Company Bank BSB</option></select></label><label>Value<input name="value" required/></label><label className="form-wide">Evidence / Notes<textarea name="notes" rows={3}/></label><div className="form-wide"><button type="submit">Save Setting</button></div></form><section className="panel table-wrap"><h3>Current Settings</h3><table className="data-table"><thead><tr><th>Key</th><th>Value</th><th>Notes</th><th>Updated</th></tr></thead><tbody>{settings.map((row:any)=><tr key={row.key}><td>{row.key}</td><td>{row.value}</td><td>{row.notes||"—"}</td><td>{row.updatedAt||"—"}</td></tr>)}</tbody></table></section></>;
}
