"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Pacific/Port_Moresby",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const money=(n:number)=>new Intl.NumberFormat("en-PG",{style:"currency",currency:"PGK",minimumFractionDigits:2}).format(n);
type Account={id:string;code:string;name:string};
export default function GeneralLedgerPage(){
 const [accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(today),[data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/reports/general-ledger/accounts").then(r=>r.json()).then(p=>{if(!p.ok)throw new Error(p.error);setAccounts(p.accounts||[])}).catch(()=>setError("Account list could not be loaded"));},[]);
 const load=useCallback(async()=>{if(!accountId)return;setError("");const q=new URLSearchParams({accountId,to});if(from)q.set("from",from);const r=await fetch(`/api/reports/general-ledger?${q}`,{cache:"no-store"});const p=await r.json();if(!r.ok||!p.ok){setError(p.error||"General Ledger could not be loaded");setData(null);return}setData(p.ledger)},[accountId,from,to]);
 return <><div className="page-head"><div><h2>General Ledger</h2><p className="small">Posted journal movements, opening balance and running balance by GL account.</p></div><div className="page-head-actions"><Link className="button-link secondary-link" href="/reports/trial-balance">Trial Balance</Link><Link className="button-link secondary-link" href="/reports">Financial Reports</Link></div></div>
 <section className="panel"><div className="form-grid"><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="button-row"><button onClick={()=>void load()} disabled={!accountId}>Run General Ledger</button></div></section>
 {error&&<section className="panel warning-panel">{error}</section>}
 {data&&<section className="panel table-wrap"><div className="form-title-row"><div><h3>{data.account.code} — {data.account.name}</h3><p className="small">{data.period.from||"Beginning"} to {data.period.to}</p></div><strong>Opening {money(data.openingBalance)} · Closing {money(data.totals.closingBalance)}</strong></div><table className="data-table" style={{minWidth:1100}}><thead><tr><th>Date</th><th>Journal ID</th><th>Document</th><th>Reference / Description</th><th>Debit</th><th>Credit</th><th>Running Balance</th></tr></thead><tbody>{data.rows.map((r:any)=><tr key={r.id}><td>{r.date}</td><td><Link href={`/journals/${r.journalId}`}><strong>{r.journalCode}</strong></Link></td><td>{r.documentNo||r.documentType||"—"}</td><td>{r.reference||r.description||"—"}</td><td>{r.debit?money(r.debit):"—"}</td><td>{r.credit?money(r.credit):"—"}</td><td>{money(r.balance)}</td></tr>)}{!data.rows.length&&<tr><td colSpan={7}>No posted activity for this account and period.</td></tr>}<tr><th colSpan={4}>Period Total</th><th>{money(data.totals.debit)}</th><th>{money(data.totals.credit)}</th><th>{money(data.totals.closingBalance)}</th></tr></tbody></table></section>}</>
}